version: "3"

services:

  fakedomain:
    build: .
    image: fakedomain
    volumes:
       - ./config:/opt/config
    ports:
       - 8888:8888

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./var/certs:/opt/certs:ro

