version: '3'
services:
  fakedomain-proxy:
     build:
       context: .
     volumes:
       - ./var/certs:/opt/certs
       - ./config.yaml:/config.yaml:ro
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
     ports:
       - 8888:8888
